In [1]:
# -*- coding: utf-8 -*-
# Initial setup

%precision 3

import numpy as np

In [41]:
l = np.array([[1, 2], [3, 4], [5, 6]])
m = np.array([[11, 12, 13], [13, 14, 15], [15, 16, 17]])
n = np.array([[1, 1], [2, 2]])

In [42]:
# Element-wise operations
print 1 + l
print m * 2
print 1 / n.astype('float')

[[2 3]
 [4 5]
 [6 7]]
[[22 24 26]
 [26 28 30]
 [30 32 34]]
[[ 1.   1. ]
 [ 0.5  0.5]]


In [43]:
print l.max(axis=0) # Column-wise max
print l.argmax(axis=1) # Returns indices
print m.sum()
print np.exp(m)
print n > 1
print n[n > 1]

[5 6]
[1 1 1]
126
[[    59874.1417152     162754.791419      442413.39200892]
 [   442413.39200892   1202604.28416478   3269017.37247211]
 [  3269017.37247211   8886110.52050787  24154952.7535753 ]]
[[False False]
 [ True  True]]
[2 2]


In [48]:
print l.T
# print np.linalg.inv(m)
print l.dot(n)

[[1 3 5]
 [2 4 6]]
[[ 5  5]
 [11 11]
 [17 17]]
