In [1]:
# -*- coding: utf-8 -*-
# Initial setup

%precision 3

import numpy as np

In [6]:
m = [[1, 2], [3, 4], [5, 6]]
m = np.array(m)
m.shape

(3, 2)

In [9]:
m[0, 1] # Returns an item at 1st row and 2nd column

2

In [15]:
m[:, 1] # Returns 2nd columns at all rows

array([2, 4, 6])

In [25]:
np.vstack([m, m])

array([[1, 2],
       [3, 4],
       [5, 6],
       [1, 2],
       [3, 4],
       [5, 6]])

In [26]:
np.hstack([m, m])

array([[1, 2, 1, 2],
       [3, 4, 3, 4],
       [5, 6, 5, 6]])

In [40]:
path = 'machine-learning-ex1/ex1/'
ex1data1 = [map(float, line.strip().split(',')) for line in open(path + 'ex1data1.txt')]
ex1data1 = np.array(ex1data1)
rows, cols = ex1data1.shape
print 'ex1data1 has {} rows and {} cols as {}'.format(rows, cols, ex1data1.dtype)

ex1data1 has 97 rows and 2 cols as float64
